- keg/generator.py
- keg/image_definition.py
- keg/keg.py
- test/data/data/base/jeos/leap/config.yaml
- test/data/data/base/jeos/leap/packages.yaml
- test/data/data/defaults/profile_defaults.yaml
- test/data/images/defaults.yaml
- test/data/images/leap/15.2/image.yaml
- test/data/images/leap/profiles.yaml
- test/data/images/leap_single_build/image.yaml
- test/unit/image_definition_test.py
- test/unit/keg_test.py
- tox.ini
This patch is many fold but reviewable on a per commit basis
**Added test data infrastructur**
For testing components of keg we need a test data infrastructure. The proposed data is based on composing a Leap 15.2 JeOS image. The tests when you read them shows how I understand the purpose of the composing code and its modes
**Add tests for KegImageDefinition class**
The KegImageDefinition class takes a keg image definition and composes/includes recursively all data that belongs to this image definition. The component data is taken  from the provided data tree. This commit tests the  traversal of data and checks on the expected output.  This Fixes #11
**Temporary disable 100% code coverage in tests**
Due to the unfortunate merge of code that was not covered by tests the github actions …
> Test and update image definition

- kiwi_keg/generator.py
- kiwi_keg/image_definition.py
- kiwi_keg/kiwi_description.py
- test/unit/generator_test.py
- test/unit/image_definition_test.py
Make sure obvios errors like recipe path does not exist
or schema template was not found are catched by keg.
Also make sure validation errors from KIWI are part of
the log output
> Improve overall error checking

- .virtualenv.dev-requirements.txt
- doc/DC-keg
- doc/Makefile
- doc/source/commands/keg.rst
- doc/source/conf.py
- doc/source/index.rst
- doc/source/installation.rst
- doc/source/overview.rst
- doc/xml/book.xml
- tox.ini
This change is two fold
**Added Keg Documentation**
Added overview chapter and update manual page as well as say some words how to install
keg. This Fixes #7
**Added doc_suse tox target**
Build SUSE documentation from sphinx based project. This will be the docs that gets published on
documentation.suse.com. The suse target is auto generated from the ReST sources. The doc team
can easily manage the data you find in doc/xml at the time we point them to this github repo
> Add documentation

- doc/source/commands/keg.rst
- doc/xml/book.xml
- kiwi_keg/generator.py
- kiwi_keg/keg.py
- kiwi_keg/kiwi_description.py
- test/data/keg_output_invalid/config_invalid.xml
- test/data/keg_output_xml/config.kiwi
- test/data/keg_output_xml/config.xml
- test/data/keg_output_yaml/config.kiwi
- test/data/keg_output_yaml/config.yaml
- test/unit/generator_test.py
- test/unit/keg_test.py
- test/unit/kiwi_description_test.py
The KIWI validation does not preserve comments after validation
as they have no meaning for the processing of the image description.
However for OBS comments are treated as project configurations
and therefore the toplevel comments if present must be added back.
This Fixes #19
> Preserve XML comments

- kiwi_keg/image_definition.py
- kiwi_keg/utils.py
- test/unit/utils_test.py
Keys from upper levels may be overwritten in lower levels, but adding subsequent data modules may revert that by merging upper level dict files again. This commit prevents duplicate merging.
> Properly support overwriting of keys

- .bumpversion.cfg
- doc/source/conf.py
- kiwi_keg/file_utils.py
- kiwi_keg/image_definition.py
- kiwi_keg/keg.py
- kiwi_keg/version.py
- test/unit/file_utils_test.py
- test/unit/image_definition_test.py
- test/unit/keg_test.py
Instead of looking for directories with a image.yaml, try to construct an image definition from all leaf directories in 'images'. This adds basic validation of the image definitions.
Add image name, description, and version number to output.
The formatting uses hard-coded field widths, which isn't ideal, but "happens" to work well for images currently defined in keg-recipes. I can invest a little time in making it nicer if people think it's worth it.
> Improve list-recipes

- doc/DC-keg
As the SUSE doc team is currently updating all content on doc.suse.com to rebranded stylesheets, we'd like to update this repo to those stylesheets too.
Be aware that the new stylesheets are currently only officially available for SLE 15 SP3/Leap 15.3 and Tumbleweed. To use them in any other OS release, you currently still need to enable the Documentation:Tools OBS repo.
If that works for you, we'd be happy if this could be merged.
(Sorry about the branch name, I should not have used the web interface.)
> documentation DC: Update to new suse2021 stylesheets

- .virtualenv.dev-requirements.txt
For static type checking many modules startet to create
library stubs packages to contain the types, like header
files in C/C++. This commit installs the missing stubs
package to the development environment
> Fix missing mypy library stubs

- doc/source/commands/keg.rst
- doc/source/conf.py
- doc/source/data_modules.rst
- doc/source/image_definition.rst
- doc/source/index.rst
- doc/source/overview.rst
- doc/source/recipes_basics.rst
This PR adds sections `Recipes Basics`, `Image Definition`, and `Data Modules` which describe the fundamental data structure keg uses and how it merges data. The `Data Modules` part may be a bit hard to read, not sure. I thought it might be useful to have all specifications in one place rather than broken into several bits, but it means you'll probably have to scroll to see the explanation below. Feedback welcome.
> Add documentation on keg recipes data strucutre

- kiwi_keg/file_utils.py
- kiwi_keg/generator.py
- kiwi_keg/image_definition.py
- kiwi_keg/script_utils.py
- test/data/images/leap_nested_profiles/15.2/image.yaml
- test/data/images/leap_nested_profiles/profiles.yaml
- test/unit/generator_test.py
- test/unit/keg_test.py
Add support for nested profiles in multi-build image definitions.
This potentially allows for shorter package sections, less duplication in overlay archives, and shorter config.sh scripts.
This commit also streamlines the produced overlay archives by not including directories multiple times.
> Nested profiles

- kiwi_keg/image_definition.py
Do not require image definition dict to have an 'arch' key. Architecture build configuration is now handle via generic image config comments.
This is required for https://github.com/SUSE-Enceladus/keg-recipes/pull/40.
> Drop check for 'arch' key

- kiwi_keg/generator.py
Skip profiles that contain nested profiles when generating _multibuild.
> Do not include base profiles in _multibuild file

- kiwi_keg/obs_service/compose_kiwi_description.py
- kiwi_keg/obs_service/compose_kiwi_description.service
- test/unit/obs_service/compose_kiwi_description_test.py
This commit implements the actual keg call and store
of result image data in the output directory from
which OBS auto commits the data to the project if
called on the remote side. This Fixes #68
> Complete obs service

- .virtualenv.dev-requirements.txt
- test/unit/kiwi_description_test.py
Use xmldiff to compare generated config.xml to expected version instead of filecmp to avoid failing test due to immaterial differences in indentation.
> Use xmldiff to compare generated config.xml to expected

- kiwi_keg/generator.py
- kiwi_keg/image_definition.py
- kiwi_keg/keg.py
- kiwi_keg/obs_service/compose_kiwi_description.py
- test/unit/generator_test.py
- test/unit/image_definition_test.py
- test/unit/keg_test.py
- test/unit/obs_service/compose_kiwi_description_test.py
- test/unit/source_info_generator_test.py
Instead of additional data roots only, support additional full recipes roots.
This allows to amend image definitions and add more schema templates.
Also changes obs_service to support arbitrary number of repos.
> Support multiple full recipes roots

- kiwi_keg/changelog_generator/generate_recipes_changelog.py
- kiwi_keg/keg.py
- kiwi_keg/source_info_generator.py
- test/data/keg_output_source_info/log_sources
- test/data/keg_output_source_info/log_sources_broken
- test/data/keg_output_source_info/log_sources_fake
- test/data/keg_output_source_info/log_sources_nested_one
- test/data/keg_output_source_info/log_sources_nested_other
- test/data/keg_output_source_info/log_sources_other
- test/unit/changelog_generator/generate_recipes_changelog_test.py
This PR changes the source info generator to store the used recipes root directories in the generated logs, and the changelog generator to use that info to automatically select the appropriate path to the git repo. The previous implementation relied on the repo path to be supplied on the command line and didn't support multiple repositories.
> Support multiple roots for changelog generation

- Makefile
- kiwi_keg/changelog_generator/generate_recipes_changelog.py
- kiwi_keg/obs_service/compose_kiwi_description.py
- kiwi_keg/obs_service/compose_kiwi_description.service
- package/python-kiwi_keg-spec-template
- setup.py
- test/unit/changelog_generator/generate_recipes_changelog_test.py
- test/unit/obs_service/compose_kiwi_description_test.py
This extends the OBS keg source service to support automatically updating the change log file. Change log is stored in `changes.yaml` for single-build and `$flavor.changes.yaml` for multi-build images. Applicable commit messages from the recipes repository or repositories are selected via keg's source tracking mechanism, and are limited by revision specification stored in the OBS package in `_keg_revisions`, which is automatically updated when a new change log is generated. This filters out old commit messages. Change logs added to the change log files are namespaced with the image version, which is automatically incremented at patch level. This can be disabled in case manually setting the version number is desired.
> Add support for change log generator to OBS source service

- kiwi_keg/obs_service/compose_kiwi_description.py
- kiwi_keg/obs_service/compose_kiwi_description.service
- test/unit/obs_service/compose_kiwi_description_test.py
Check start commit hashes from _keg_revisions against head commit hashes to determine whether the repositories have received new commits and abort if not. This allows the service to run regardless, without creating pointless version bumps.
> OBS service: abort on no source changes

- kiwi_keg/changelog_generator/generate_recipes_changelog.py
- kiwi_keg/obs_service/compose_kiwi_description.py
- test/unit/changelog_generator/generate_recipes_changelog_test.py
- test/unit/obs_service/compose_kiwi_description_test.py
If the image does not have any changes (i.e. generated change logs for all flavors are empty), abort and delete all generated files.
The current implementation only detects if the repositories don't have new commits, but since most commits in `keg-recipes` are likely to only affect a subset of all images, this won't be enough to prevent unnecessary version bumps and rebuilds. This PR adds support to handle this situation properly.
> compose_kiwi_description: abort on empty change logs

- kiwi_keg/obs_service/compose_kiwi_description.py
- kiwi_keg/obs_service/compose_kiwi_description.service
- test/unit/obs_service/compose_kiwi_description_test.py
Convert flag parameters 'disable-version-bump', --disable-changelog-update', '--disable-revisions-update', and '--force' to string type parameters. OBS src service cannot handle flags.
Add parameter '--image-version' to set image version directly.
> Obs service convert params

- kiwi_keg/image_definition.py
- kiwi_keg/image_schema.py
- test/data/broken/images/broken-config/image.yaml
- test/data/broken/images/broken-overlay/image.yaml
- test/data/output/leap-jeos-single-platform/config.kiwi
- test/data/output/leap-jeos/config.kiwi
Drop support for 'preferences' to be list or dict. dict could be used for single-build image descriptions but it made the code a bit more complex in exchange for a very small convenience benefit.
Also setting the image version was broken for dict type 'preferences'.
> require 'preferences' section to be a list

- kiwi_keg/obs_service/compose_kiwi_description.py
- kiwi_keg/obs_service/compose_kiwi_description.service
Add support for setting generate multibuild file parameter to src service.
This can be useful if you want to use a custom `_multibuild` with your image description, for instance if you have a debug profile you don't necessarily want to build in all environments.
> Support multibuild parameter in src service

- package/python-kiwi_keg-rpmlintrc
- package/python-kiwi_keg-spec-template
- package/python-kiwi_keg.spec
Drop rpmlintrc disabling duplicate files check.
Generated egg info potentially contains two empty files (except for a newline) that triggers an rpmlint warning. This doesn't appear to happen in Tumbleweed which makes including the lintrc to produce an error. Not including it produces a warning in older distros. We could account for that but I think it's not worth it just to silence an rpmlint warning so we might as well drop it.
> Drop rpmlintrc

- doc/source/commands/generate_recipes_changelog.rst
- doc/source/commands/keg.rst
- doc/source/installation.rst
- doc/xml/book.xml
This fixes a couple of issues in the man page sources that resulted in a broken docbook source.
Also includes an update of the installation section reflecting package name change and inclusion of keg in Tumbleweed, and a typo fix.
I also regenerated the docbook file so up-to-date SUSE branded documentation pages can be generated.
> Documentation fixes and docbook source refresh

- package/python-kiwi-keg.spec
Switch the source to use kiwi-keg to be more consistent with the package name and reduce reader/user to keep track of "_" vs. "-"
> Nameing consistency

- package/python-kiwi-keg.spec
Use keg instead of kiwi-keg as source directory name. This avoids an issue with the OBS tar source service.
> Use keg instead of kiwi-keg as source dir name

- .github/workflows/ci-publish-to-pypi.yml
Since python 3.6 was dropped from ubuntu-latest, use 3.10 for the publishing pipeline.
> Use python 3.10 for publishing

- kiwi_keg/image_definition.py
- kiwi_keg/keg.py
- test/unit/keg_test.py
Make list operation faster by not fully populating all image definitions. Find longest strings to output and size output fields accordingly for better format.
Note: This skips validation of image definitions, which with the number of image definitions in keg-recipes just takes way too long for a simple list command. The version number is also not necessarily available in the output (only when defined in `images/`, which for instance is not the case in keg-recipes), but I think that's ok and version numbers can be overwritten anyway.
> Improve list command

- kiwi_keg/image_schema.py
- test/data/broken/images/broken-config/image.yaml
- test/data/broken/images/broken-overlay/image.yaml
This PR removes the expected namespace from the `packages` section from the image dictionary schema and instead handles namespaces transparently in the schema validator by creating a temporary dict in which each namespaced dict is copied into and then validated against the schema. This allows namespaces to be used basically anywhere in the image dict, and also makes them completely optional. It also validates data that was previously in an unexpected namespace before and hence ignored as an extra key.
Also includes minor adjustments (`displayname` is now optional, and an optional `drivers` section is now validated).
Namespaces outside the image dictionary (i.e. in the `config` and `archive` sections) are still mandatory as they are handled differently in the code. Not sure whether it's …
> Handle namespaces transparently in schema validation

- .coveragerc_py36
- .virtualenv.dev-requirements-py36.txt
- kiwi_keg/tools/compose_kiwi_description.py
- kiwi_keg/tools/generate_recipes_changelog.py
- obs/compose_kiwi_description.service
- package/python-kiwi-keg.spec
- setup.py
- test/unit/tools/compose_kiwi_description_test.py
- test/unit/tools/generate_recipes_changelog_test.py
- tox.ini
Add support for generating json and osc-style ('osc vc') formats to change log generator.
Add config parameter to compose_kiwi_description to select change log format.
Add config parameter to compose_kiwi_description that allows defining a change log entry for new images.
Add support to compose_kiwi_description for converting change log formats when merging old and new change logs (all conversions supported except from osc).
> Update change log handling

- kiwi_keg/tools/compose_kiwi_description.py
- obs/compose_kiwi_description.service
A couple of small fixes:
- Fix new-image-change parameter name in OBS .service file.
- Fix typos in new-image-change parameter description in OBS .service file and compose_kiwi_description help.
> Fix new-image-change parameter

- kiwi_keg/image_schema.py
Allow 'preferences' key of the image dict to be of type dict additionally to type list. In a single-build setup, there is only one preferences section, and having that as a dict makes composing it from different sources more convenient.
> Allow preferences key to be type dict

- doc/source/obs_source_service.rst
Add the commands to install the source service and run the service with osc.
> Add source service commands

- doc/xml/book.xml
For our doc portal to come, all documents published on documentation.suse.com need a certain amount of metadata (to make them filterable, findable etc.). Find the list of metadata that we have agreed on beforehand in our [internal page](https://confluence.suse.com/display/documentation/Adding+metadata+to+all+SUSE+documentation).
I have added the required metadata for the Keg Reference Guide. 
Please review and merge.
> Doc: Add metadata needed for doc portal
