keg/exceptions.py, keg/kiwi_description.py, test/data/keg_description/config.kiwi, test/data/keg_description/config_invalid.kiwi, test/unit/kiwi_description_test.py
The KiwiDescription class allows to validate and markup translate
a given KIWI description file against the KIWI API. The translation
through the KIWI API includes automatic XSLT processing into the
schema used by KIWI at call time and pretty formats the output
=> Added KiwiDescription class

keg/exceptions.py, keg/generator.py, keg/image_definition.py, keg/keg.py, keg/kiwi_description.py, keg/logger.py, keg/logger_filter.py, keg/template_functions.py, keg/utils.py, keg/version.py, keg/yaml_utils.py
Initial code drop, supports generation of config.kiwi and config.sh.
=> Initial code drop

.virtualenv.dev-requirements.txt, README.rst
=> Add information for contributing

.virtualenv.dev-requirements.txt, kiwi_keg/image_definition.py, tox.ini
=> Add type hint checker

kiwi_keg/generator.py, kiwi_keg/image_definition.py, kiwi_keg/utils.py, test/unit/image_definition_test.py, test/unit/utils_test.py
Turn the code into a class.
Remove code duplication in some methods
Update a method name
=> Refactor utils

kiwi_keg/image_definition.py
- Add update profiles method
- Add update contents method
=> Update image definition populate methods

kiwi_keg/image_definition.py, kiwi_keg/keg.py, kiwi_keg/utils.py, test/unit/image_definition_test.py, test/unit/keg_test.py
=> Add option to list available recipes

kiwi_keg/utils.py
With --verbose set print information which file from the image definition was read in the order of their reading.
=> Added information about data read from image tree

doc/source/index.rst, doc/xml/book.xml
After a converstation with Stefan Knorr from the doc team
we agreed on updating the Keg title to be more specific.
In addition a sub-title was added to outline what keg is
good for
=> Update documentation title

kiwi_keg/generator.py, kiwi_keg/keg.py, test/data/keg_output/_multibuild, test/unit/generator_test.py, test/unit/keg_test.py
This adds support for creating _multibuild files for use with OBS. Can be disabled if undesired.
=> Add support for _multibuild creation

.bumpversion.cfg, doc/source/conf.py, kiwi_keg/version.py
Bump version number in preparation of package update.
=> Bump version: 1.0.0 → 1.1.0

kiwi_keg/image_definition.py
Copy profile parameter section from the base profile (if exists) into nested profiles and remove it from the base profile. This allows to have profile parameters in the base section rather than requiring all profile parameter containing sections to be in the nested profiles, potentially reducing duplication.
=> Support profile parameters in base profiles

kiwi_keg/script_utils.py, test/data/keg_output/config.sh, test/data/keg_output/config_fallback_header.sh
Do not append newlines at the end of sections.
Insert newline between if blocks.
Insert newline between scriptlets.
=> Better spacing in config.sh

kiwi_keg/changelog_generator/generate_recipes_changelog.py, test/data/keg_output_source_info/log_sources_fake, test/unit/changelog_generator/generate_recipes_changelog_test.py, test/unit/source_info_generator_test.py
Add a script that generaters a changelog (text and yaml format supported) from
the git commit history and the source info log produced by keg.
=> Add changelog generator

kiwi_keg/obs_service/compose_kiwi_description.py, test/unit/obs_service/compose_kiwi_description_test.py
Read old image version from existing config.kiwi rather than generated one and pass it to keg generator.
=> obs_service: Fix version bump feature

kiwi_keg/changelog_generator/generate_recipes_changelog.py, test/unit/changelog_generator/generate_recipes_changelog_test.py
Include a time stamp for each change in the change log.
=> changelog generator: output dates in YAML changelog

kiwi_keg/image_schema.py
'config: files' key is list type.
=> fix for schema validation

README.rst, doc/DC-keg, doc/source/changelog_generator.rst, doc/source/commands/generate_recipes_changelog.rst, doc/source/commands/keg.rst, doc/source/data_modules.rst, doc/source/image_definition.rst, doc/source/installation.rst, doc/source/obs_source_service.rst, doc/source/overview.rst, doc/source/recipes_basics.rst, kiwi_keg/obs_service/compose_kiwi_description.service
Update or better partial rewrite of the user documentation, necessary due to the `minikeg` merge which changed recipes structures and how keg generates output significantly. Also includes some hopefully improved rewording and minor fixes.
=> Documentation update

.github/workflows/ci-testing.yml, test/unit/obs_service/compose_kiwi_description_test.py, tox.ini
Fix a previously non functional assertion.
Remove a previously non functional assertion for a function call that was not to be executed in that circumstance anyway.
=> Fix unit tests of OBS src service module

README.rst
Feel free to adjust the formatting; I just think it would be helpful to link the published docs.
=> Add a link to docs, to the README

.virtualenv.dev-requirements.txt, README.rst, package/python-kiwi-keg.spec, setup.py, test/data/output/invalid/config_invalid.xml, test/data/output/xml/config.kiwi, test/data/output/xml/config.xml, test/data/output/xml/config2.xml, test/data/output/yaml/config.kiwi, test/data/output/yaml/config.yaml, test/unit/changelog_generator/generate_recipes_changelog_test.py, test/unit/file_utils_test.py, test/unit/generator_test.py, test/unit/keg_test.py, test/unit/kiwi_description_test.py, test/unit/logger_test.py, test/unit/obs_service/compose_kiwi_description_test.py, tox.ini
A few packaging/integration related updates.
=> Misc packaging/integration updates

doc/source/image_definition.rst, kiwi_keg/generator.py, kiwi_keg/image_schema.py, kiwi_keg/keg.py, test/data/images/leap-jeos/content.yaml, test/data/output/leap-jeos/_constraints, test/data/output/leap-jeos/log_sources_Blue, test/data/output/leap-jeos/log_sources_Orange, test/unit/file_utils_test.py, test/unit/generator_test.py
Can be used for managing files like `_constraints` in the recipes repo.
=> Add support for generating custom XML files

setup.py
Set author e-mail address in setup.py to public team address.
=> Fix e-mail address in setup.py

kiwi_keg/dict_utils.py, kiwi_keg/generator.py
Two tiny improvements:
- Skip comments in XML output for namespaces that have no name
- Better error reporting on merge errors
=> Minor fixes

kiwi_keg/image_definition.py, kiwi_keg/keg.py, test/data/images/leap-jeos-single-platform/content.yaml
Support dict type preferences section in list command.
=> Allow preferences to be dict in list command

.virtualenv.dev-requirements.txt, .virtualenv.requirements.txt, doc/source/conf.py, setup.py
Formatting fixes in doc/source/conf.py and setup.py.
Remove unused imports.
Update requirements so no deprecated packages are included.
=> Minor cleanup
